const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const {firefox}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const base=process.env.PLAYBOOK_TEST_URL||'http://127.0.0.1:8765';
const key='us-china-playbook.tools.v1',bk='us-china-playbook.bookmarks.v1';
(async()=>{
const browser=await firefox.launch({headless:true,env:{...process.env,MOZ_DISABLE_CONTENT_SANDBOX:'1',MOZ_DISABLE_GMP_SANDBOX:'1',MOZ_DISABLE_RDD_SANDBOX:'1'}});
const c=await browser.newContext({acceptDownloads:true,viewport:{width:390,height:844}}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
const open=async(hash='')=>{await p.goto(base+'/'+hash);await p.reload();await p.locator('#status').filter({hasNotText:'正在载入'}).waitFor()};
await open();const docs=await p.evaluate(()=>docs); // lexical binding is intentionally inspected by local tests
const directoryPaths=await p.locator('#directory a[data-path]').evaluateAll(links=>links.map(a=>a.dataset.path));
assert.equal(directoryPaths.length,docs.length);assert.equal(new Set(directoryPaths).size,docs.length);
assert(directoryPaths.includes('CONTENTS.md'));
await p.getByRole('button',{name:'搜索',exact:true}).click();assert(await p.locator('#search').isVisible());
const d=docs.find(d=>d.path==='checklists/first-30-days.md'),s=d.sections.find(s=>s.taskIds.length),url='#content='+d.contentId+'&at='+s.contentId;
await open(url);await p.locator('article').waitFor();const previousScroll=await p.evaluate(()=>scrollY);await p.getByRole('button',{name:'目录与筛选',exact:true}).click();await p.getByRole('dialog').waitFor();await p.getByRole('button',{name:'返回阅读位置'}).click();assert(Math.abs((await p.evaluate(()=>scrollY))-previousScroll)<5);const first=p.locator('[data-task-id]').first();await first.check();await p.reload();await first.waitFor();assert(await first.isChecked());assert((await p.locator('#task-count').innerText()).includes('已勾选 1 /'));
await p.locator('.bookmark-button').first().click();
await p.locator('.section-actions summary').first().click();await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>{window.copy=t}},configurable:true}));await p.getByRole('button',{name:'复制小节链接'}).first().click();const share=await p.evaluate(()=>window.copy);assert(share.includes('/read/'+d.contentId+'.html#'));
await p.getByRole('button',{name:'复制引用',exact:true}).first().click();const citation=await p.evaluate(()=>window.copy);assert(citation.includes(d.title)&&citation.includes(share)&&citation.includes('访问日期'));
await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error()}},configurable:true}));await p.getByRole('button',{name:'复制小节链接'}).first().click();await p.getByText('无法自动复制，请手动复制已选中的地址。').waitFor({state:'visible'});await p.getByRole('button',{name:'复制引用',exact:true}).first().click();await p.getByText('无法自动复制，请手动复制已选中的引用信息。').waitFor({state:'visible'});assert.equal(await p.getByLabel('本小节引用信息').first().inputValue(),citation);
const report=p.getByRole('link',{name:'在 GitHub 提交本节问题 ↗'}).first();assert((await report.getAttribute('href')).includes('issues/new?'));assert((await report.getAttribute('href')).includes(d.contentId));
await open('#view=tools');await p.getByLabel('正文字号',{exact:true}).selectOption('20');await p.reload();await p.getByLabel('正文字号',{exact:true}).waitFor();assert.equal(await p.getByLabel('正文字号',{exact:true}).inputValue(),'20');
const dlPromise=p.waitForEvent('download');await p.getByRole('button',{name:'导出阅读备份'}).click();const dl=await dlPromise;const backup=JSON.parse(await fs.readFile(await dl.path(),'utf8'));assert.equal(backup.bookmarks.items.length,1);assert.equal(Object.values(backup.tools.tasks).filter(Boolean).length,1);
await p.locator('#backup-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await p.getByText('文件格式无效、版本不支持或文件过大。没有更改任何本地数据。').waitFor({state:'visible'});assert.equal(await p.evaluate(bk=>JSON.parse(localStorage.getItem(bk)).items.length,bk),1);assert.equal(await p.evaluate(key=>Object.values(JSON.parse(localStorage.getItem(key)).tasks).filter(Boolean).length,key),1);
await p.evaluate(({key,bk})=>{localStorage.removeItem(key);localStorage.removeItem(bk)},{key,bk});await p.reload();await p.locator('#backup-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.getByRole('button',{name:'合并收藏',exact:true}).click();await p.getByRole('button',{name:'合并收藏',exact:true}).click();assert.equal(await p.evaluate(bk=>JSON.parse(localStorage.getItem(bk)).items.length,bk),1);await p.getByRole('button',{name:'合并清单勾选'}).click();
p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'恢复阅读位置'}).click();assert(await p.getByText('阅读位置已恢复。').isVisible());
p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'恢复阅读设置'}).click();assert.equal(await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).font,key),20);
await open(url);assert(await p.locator('[data-task-id]').first().isChecked());
// A stale tab must not overwrite a newer value; a separate page's change reaches controls.
const other=await c.newPage();await other.goto(base+'/#view=tools');await other.locator('#status').filter({hasNotText:'正在载入'}).waitFor();await other.evaluate(({key,id})=>{const st=JSON.parse(localStorage.getItem(key));st.tasks[id]=false;localStorage.setItem(key,JSON.stringify(st))},{key,id:s.taskIds[0]});await p.waitForFunction(()=>!document.querySelector('[data-task-id]').checked);assert((await p.locator('#task-count').innerText()).includes('已勾选 0 /'));await other.close();
p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'重置本页勾选'}).click();assert.equal(await p.locator('[data-task-id]:checked').count(),0);
await p.route('**/updates.json',r=>r.fulfill({json:[{contentId:d.contentId,title:'重要修订测试',summary:'范围说明',published:'2026-09-25T00:00:00Z',url:'#view=updates'}]}));await p.evaluate(k=>{const b=JSON.parse(localStorage.getItem(k));b.items[0].savedAt='2026-01-01T00:00:00Z';localStorage.setItem(k,JSON.stringify(b))},bk);await open('#view=bookmarks');assert(await p.getByText('收藏后有重要更新（1）').isVisible());await p.unroute('**/updates.json');
await open('#view=paths');assert.equal(await p.locator('.saved-item').count(),6);await p.locator('.saved-item a').first().click();assert(await p.locator('article').isVisible());
for(const view of ['tools','paths','bookmarks'])for(const width of [320,390,1440]){await p.setViewportSize({width,height:900});await open('#view='+view);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${view} overflow ${width}`)}
// Corruption is never overwritten; quota errors undo the checkbox's optimistic state.
await p.evaluate(k=>localStorage.setItem(k,'damaged'),key);await open(url);assert(await p.locator('[data-task-id]').first().isDisabled());assert.equal(await p.evaluate(k=>localStorage.getItem(k),key),'damaged');
const qc=await browser.newContext();await qc.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota')}});const qp=await qc.newPage();await qp.goto(base+'/'+url);const qbox=qp.locator('[data-task-id]').first();await qbox.click();assert.equal(await qbox.isChecked(),false);assert(await qp.getByText('保存失败，原数据未更改。',{exact:false}).isVisible());
// Static pages work without JS, preserve all stable section anchors and disable task controls.
const nc=await browser.newContext({javaScriptEnabled:false});const np=await nc.newPage();await np.goto(base+'/read/'+d.contentId+'.html#'+s.contentId);assert(await np.locator('article').isVisible());assert.equal(await np.locator('input:not(:disabled)').count(),0);assert.equal(await np.locator('section').count(),d.sections.length);
await p.goto(base+'/read/'+d.contentId+'.html#'+s.contentId);await p.waitForFunction(id=>document.getElementById('interactive-link').href.includes(id),s.contentId);await p.locator('main details summary').click();await p.locator('main details a').last().click();await p.waitForFunction(()=>document.getElementById('interactive-link').href.endsWith(location.hash.slice(1)));
// Actual service worker/cache lifecycle with networking disabled, not mocked success.
await p.goto(base+'/offline.html');await p.getByText('已载入线上章节列表',{exact:false}).waitFor();await p.locator('#offline-filter').fill('前 30 天');await p.getByRole('button',{name:'保存离线副本'}).click();await p.getByText('章节离线副本已保存。',{exact:false}).waitFor();assert.equal(await p.locator('#offline-saved .offline-row').count(),1);
await c.setOffline(true);await p.reload();await p.getByRole('link',{name:'打开已保存章节'}).click();await p.locator('article').waitFor();await p.getByText('此章有离线副本',{exact:false}).waitFor();await p.goto(base+'/offline.html');await p.getByRole('button',{name:'删除副本'}).click();await p.getByText('已删除此章离线副本。').waitFor();assert.equal(await p.locator('#offline-saved .offline-row').count(),0);await c.setOffline(false);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: checklist persistence/reset/storage errors; share fallback; backup validation/merge; settings; paths; responsive layouts; static no-JS pages; real offline cache save/read/delete.');
})().catch(e=>{console.error(e);process.exit(1)});
